name: luba_rider
description: "A logistics app-driver"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.12
  shimmer: ^3.0.0
  country_state_city: ^0.1.6
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2
  pin_code_fields: ^8.0.1
  geolocator: ^13.0.3
  geocoding: ^3.0.0
  intl: ^0.20.2
  google_maps_flutter: ^2.12.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.5

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  image_path: "assets/images/launcher-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
#    - assets/images/home/
#    - assets/images/home/restaurant/
    - assets/images/bottom_nav_bar/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/static/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/static/Montserrat-Black.ttf
          weight: 900
